int main(void)
{
    void *ptr = calloc(7, sizeof(int));
    void *ptr2 = calloc(7, sizeof(int));

    printf("strlen(\"oeuf\") = %d\n", strlen("oeuf"));
    printf("strlen(\"\") = %d\n", strlen(""));
    //printf("strlen(NULL) = %d\n",           strlen(NULL));
    printf("strchr(\"oeuf\", 'u') = %s\n", strchr("oeuf", 'u'));
    printf("strchr(\"\", 'a') = %s\n", strchr("", 'a'));
    //printf("strchr(NULL, 0) = %s\n",        strchr(NULL, 0));
    //printf("strchr(NULL, 'd') = %s\n",      strchr(NULL, 'd'));
    printf("memset(ptr, 'd', 5) = %s\n", memset(ptr, 'd', 5));
    printf("memset(ptr, 'f', 0) = %s\n", memset(ptr, 'f', 0));
    printf("memset(ptr, 'e', 6) = %s\n", memset(ptr, 'e', 6));
    printf("memset(ptr, 'f', 7) = %s\n", memset(ptr, 'f', 7));
    //printf("memset(NULL, 'f', 7) = %p\n",   memset(NULL, 'f', 7));
    free(ptr);
    free(ptr2);
    ptr = calloc(7, sizeof(int));
    ptr2 = calloc(7, sizeof(int));
    //printf("strcmp(ptr, NULL) = %d\n",       strcmp(ptr, NULL));
    //printf("strcmp(NULL, ptr2) = %d\n",      strcmp(NULL, ptr2));
    //printf("strcmp(NULL, NULL) = %d\n",      strcmp(NULL, NULL));
    printf("strcmp(\"abc\\0\", \"ab\\0\") = %d\n", strcmp("abc\0", "ab\0"));
    printf("strcmp(ptr, ptr2) = %d\n", strcmp(ptr, ptr2));
    //printf("\nmemset(ptr, 'f', 7) = %s\n",   memset(ptr,  'e', 6));
    //printf("memset(ptr, 'f', 7) = %s\n",     memset(ptr2, 'f', 6));
    printf("\nmemcpy(ptr, ptr2, 0) = %s\n", memcpy(ptr2, ptr, 0));
    printf("memcpy(ptr, ptr2, 7) = %s\n", memcpy(ptr2, ptr, 7));
    //printf("memcpy(NULL, ptr2, 7) = %s\n",   memcpy(NULL, ptr, 7));
    //printf("memcpy(ptr, NULL, 7) = %s\n",    memcpy(ptr2, NULL, 6));
    //printf("memcpy(NULL, NULL, 7) = %s\n",   memcpy(NULL, NULL, 6));
    printf("\nmemset(ptr, 'f', 7) = %s\n", memset(ptr, 'e', 7));
    printf("memset(ptr, 'f', 7) = %s\n", memset(ptr2, 'f', 7));
    printf("\nmemmove(ptr, ptr2, 0) = %s\n", memmove(ptr2, ptr, 0));
    printf("memmove(ptr, ptr2, 7) = %s\n", memmove(ptr2, ptr, 7));
    ((char *)(ptr))[0] = 'p';
    ((char *)(ptr))[4] = 'o';
    printf("\nmemmove(ptr, ptr, 0) = %s\n", memmove(ptr, ptr, 0));
    printf("memmove(ptr+2, ptr, 5) = %s\n", memmove(ptr + 2, ptr, 5));
    printf("memmove(ptr, ptr, 0) = %s\n", memmove(ptr, ptr, 0));
    //printf("memmove(NULL, ptr2, 7) = %s\n",  memmove(NULL, ptr, 7));
    //printf("memmove(ptr, NULL, 7) = %s\n",   memmove(ptr2, NULL, 7));
    //printf("memmove(NULL, NULL, 7) = %s\n",  memmove(NULL, NULL, 7));
    printf("rindex(\"425\\0\", '5') = %s\n", rindex("42547\0", '5'));
    printf("strcasecmp(\"425\\0\", '5') = %d\n", strcasecmp("cni\0", "dNi\0"));
    printf("strcasecmp(\"425\\0\", '5') = %d\n", strcasecmp("cni\0", "eNi\0"));
    printf("strcasecmp(\"425\\0\", '5') = %d\n", strcasecmp("enI\0", "cNi\0"));
    printf("strstr(\"bon oeuf\", \"n o\") = %s\n", strstr("bon oeuf", "n o"));
    printf("strstr(\"bon oeuf\", \"oof\") = %s\n", strstr("bon oeuf", "oof"));
    //printf("strstr(\"bon oeuf\", NULL) = %s\n",                     strstr("bon oeuf", NULL));
    //printf("strstr(NULL, \"oof\") = %s\n",                     strstr(NULL, "oof"));
    printf("strpbrk(\"bon oeuf\", \"no\") = %s\n", strpbrk("bon oeuf", "no"));
    printf("strpbrk(\"bon oeuf\", \" \") = %s\n", strpbrk("bon oeuf", " "));
    printf("strpbrk(\"bon oeuf\", \"f\") = %s\n", strpbrk("bon oeuf", "f"));
    printf("strpbrk(\"bon oeuf\", \"x\") = %s\n", strpbrk("bon oeuf", "x"));
    printf("strcspn(\"bon oeuf\", \"x\") = %d\n", strcspn("bon oeuf", "x"));
    printf("strcspn(\"bon oeuf\", \"u\") = %d\n", strcspn("bon oeuf", "u"));
    printf("strcspn(\"bon oeuf\", \" \") = %d\n", strcspn("bon oeuf", " "));
    printf("strncasecmp(\"425\\0\", '5', 0) = %d\n", strncasecmp("cni\0", "dNi\0", 0));
    printf("strncasecmp(\"425\\0\", '5', 5) = %d\n", strncasecmp("cni\0", "eNi\0", 48));
    printf("strncasecmp(\"425\\0\", '5', 5) = %d\n", strncasecmp("cnI\0", "cNe\0", 1));
    printf("strspn(\"bon oeuf\", \"bon \") = %d\n", strspn("bon oeuf", "bon \0"));
    printf("strspn(\"bon oeuf\", \"u\") = %d\n", strspn("bon oeuf", "u\0"));
    printf("strspn(\"bon oeuf\", \" \") = %d\n", strspn("bon oeuf", " \0"));
    printf("strcasestr(\"bon oeuf\", \"n o\") = %s\n", strcasestr("bon oeuf", "N O"));
}
